apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: w0vnog6dg-python-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/w0vnog6dg-python-gitops